app:
  timezone: "Europe/Paris"
  delivery_time: "10:00"       # heure d’envoi locale
  mode: "equilibre"            # ton mode B
  daily:
    album_spotlight: 1
    playlist_size: 15
    playlist_visibility: "public"   # public/private
    create_new_playlist_each_day: true

selection_rules:
  freshness_window_days: 7
  per_artist_cap: 2
  exclude_reissues_deluxe: true
  bias_france_bonus: 0.10       # +10%
  allow_strong_singles: true
  explicit_allowed: true
  missing_on_deezer_strategy: "replace_with_other_from_same_artist"
  fill_strategy_if_under_15: "adventurous_picks"

consensus:
  # Règle “équilibré” : ≥1 éditorial + ≥1 agrégateur, ou flag fort + métriques secondaires
  editorial_sources_required: 1
  aggregator_sources_required: 1
  strong_flag_allows_entry: true  # ex: Bandcamp Album of the Day / Notable

scoring_weights:
  editorial_presence: 0.35        # Pitchfork/FACT/HipHopDX/BandcampDaily
  aggregator_presence: 0.25       # AOTY/ADM (et/ou note si dispo)
  freshness_boost: 0.20           # sorties récentes dans la fenêtre 7j
  strong_flags: 0.15              # Bandcamp “New & Notable”, “Album of the Day”
  france_bias: 0.05               # bonus si FR (label/artiste pays=FR)
  # (on garde ça simple pour V1)

sources:
  aoty:
    enabled: true
    strategy: "rss"               # flux “New Releases”, “Highest Rated”, etc.
  anydecentmusic:
    enabled: true
    strategy: "page"              # “Recent/Just In” (parsing léger)
  bandcamp_daily:
    enabled: true
    strategy: "page"              # Latest / Album of the Day / Essential
  pitchfork:
    enabled: true
    strategy: "rss"               # album/track reviews, Best New Music
  fact_magazine:
    enabled: true
    strategy: "rss_or_page"
  hiphopdx:
    enabled: true
    strategy: "page"              # reviews/singles index
enrichment:
  musicbrainz:
    enabled: true
    rate_limit_per_sec: 1
